### ISSUE TITLE
Termux main repo

### ISSUE THREAD

**Issue by dukealexanderthefirst** [dukealexanderthefirst/calcsh#1]
@fornwall Could you please add this to the main package repo? I would be thrilled!

**Comment by fornwall** [comment]
Hello! I think you should rather have a look at [Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects/), since if you package a python package like that everyone who has python installed can install your package, regardless of what Linux distribution is used, or even on e.g. Windows and Mac!

**Comment by dukealexanderthefirst** [comment]
@fornwall While that is true, I've always wanted to have my package in @termux so I would be much obliged if you could maybe tell me about the steps I need to take to achieve this!😊😌

**Comment by dukealexanderthefirst** [comment]
@fornwall Restarting my own private repo soon anyway!
